### ISSUE TITLE
perform automated checks on all live proposals

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/governance-seatbelt#1]
run best practices checks against live proposals and publishes results (on a schedule)

ideally this is an extensible framework to which new checks are easily added. the framework should expose some capabilities to each check, such as passing proposals, simulating arbitrary transactions, changing timestamps, updating token balances, downloading code from etherscan and running processes against them (solidity compiler, slither, etc.)

some ideas for an initial set of checks
- Proposal can be successfully executed at expected timestamp x (simulate proposal)
  - list all state changes as a result of executing each step of the proposal
- Decode all target calldata and display arguments, same or better than the interface does
- any solidity compiler warnings from compiling the contracts (fetched from etherscan)
- all contracts touched by the proposal and any state updates are verified on etherscan
- print out all slither warnings

all these checks can be compiled into a report which is exposed on the reports branch

**Comment by mds1** [comment]
Created https://github.com/Uniswap/governance-seatbelt/issues/48 and https://github.com/Uniswap/governance-seatbelt/issues/49 to track the two unchecked items above, so closing this in favor of those
