### ISSUE TITLE
reports: consider saving reports as GitHub artifacts instead of on a special branch

### ISSUE THREAD

**Issue by mds1** [Uniswap/governance-seatbelt#44]
Tradeoffs:
- Allows you to view artifacts from a specific workflow run
- CI runs happening on the same time/overlapping will never conflict and overwrite each other
- Ideally artifacts can be viewable directly as markdown files on github, i.e. inconvenient if you have to download the files locally to view them

see (h/t @moodysalem for the links):
- https://github.com/actions/upload-artifact
- https://stackoverflow.com/questions/67507373/how-to-attach-a-markdown-page-to-github-actions-workflow-run-summary/67516774#67516774

**Comment by mds1** [comment]
One additional downside to the current approach is that sometimes report writing in the github workflows has been failing. I haven't looked into this to see why/when it occurs, but it does seem to only occur sporadically

**Comment by mds1** [comment]
Idle Finance proposal 20 touches a lot of contracts, and as a result the report file is is 1.7 MB. When trying to get the sha of this file to overwrite it, the GitHub API fails with:

> This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.

This causes the CI to fail. As a result I've temporarily removed Idle from the CI. Planning to tackle this issue next and add will add Idle back to CI once complete

cc @bugduino

**Comment by mds1** [comment]
@bugduino Just added Idle back! Reports are now attached to workflow runs so you'll have to view them there. Currently working on additionally generating HTML and/or PDF reports that can be embedded into/linked from the governance proposal pages without need to download markdown files

**Comment by bugduino** [comment]
Awesome! Thanks for the great work, we will test it for the next proposal
