### ISSUE TITLE
feat: OpenZeppelin Governor Support

### ISSUE THREAD

**Issue by mds1** [Uniswap/governance-seatbelt#52]
Currently only Compound GovernorBravo style governors are supported. Many projects use OpenZeppelin's [Governor](https://docs.openzeppelin.com/contracts/4.x/api/governance#GovernorCompatibilityBravo), so support should be added for that governor. Ensure both the standard and GovernorCompatibilityBravo version are supported

**Comment by mds1** [comment]
Completed by https://github.com/Uniswap/governance-seatbelt/pull/89

**Comment by julien51** [comment]
Thank you!
