### ISSUE TITLE
reports: put slither output behind an expandable block

### ISSUE THREAD

**Issue by mds1** [Uniswap/governance-seatbelt#53]
Use a `<details>`  to hide slither output by default, since it takes up a lot of space. Example

<details>
<summary>Slither report</summary>

```
slither report here
```
</details>

**Comment by moodysalem** [comment]
would love to see this for every check

**Comment by mds1** [comment]
made a note about handling that in https://github.com/Uniswap/governance-seatbelt/issues/33#issuecomment-1055896938
