### ISSUE TITLE
feat: a summary of the seatbelt output at the top of the page

### ISSUE THREAD

**Issue by asood123** [Uniswap/governance-seatbelt#58]
I find myself scrolling the page looking for green or yellow emojis. Would be cool to add all of them as a summary at the top.

**Comment by mds1** [comment]
As an alternative, how do you feel about @moodysalem's idea () that each proposal check being behind a collapsible details block? (similar to how Slither is now). This would mean the default view is just headers so the scrolling should be much easier

**Comment by mds1** [comment]
Marking this completed since the table of contents functions as this summary 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/17163988/213792307-8a20cd41-d328-4ccc-909f-fde14ad486c7.png">
